### ISSUE TITLE
Support site link on AMO leads to a 404

### ISSUE THREAD

**Issue by Gitoffthelawn** [javascriptf/chrome-attention-training#4]
The support site link on [AMO](https://addons.mozilla.org/firefox/addon/attention-training/) for this extension leads to a 404.  If you like, you can simply replace it with:  
https://github.com/javascriptf/chrome-attention-training

**Comment by wolfram77** [comment]
Wow someone commented. I checked it, and it is already redirecting to this repo.

**Comment by Gitoffthelawn** [comment]
I haven't yet looked into exactly why, but for me, it goes to:  
https://github.com/javascriptf/chrome-attention-training%23readme

The hashtag is getting converted to its percent-encoded equivalent, and for some reason, GitHub can't handle that URI syntax, which leads to a 404.

**Comment by wolfram77** [comment]
Hi @Gitoffthelawn 

It seems to be going to 

```
https://prod.outgoing.prod.webservices.mozgcp.net/v1/5afad19ca9ad05539b9a919322317ef32e062ec80394ceacede59f8c5ef13ce0/https%3A//github.com/javascriptf/chrome-attention-training%23readme
```

Which, for Opera, Chrome, and Edge redirects to

```
https://github.com/javascriptf/chrome-attention-training#readme
```

Does it not work for Firefox?

**Comment by Gitoffthelawn** [comment]
Hi @wolfram77 

In Firefox, the `%23` isn't getting converted into a hashtag.  I haven't looked at why this is the situation, or how many users it may affect.  I'm busy with other stuff, so it was more time-efficient to simply remove the `%23readme` to ensure the link would work for everyone.  Of course, it's not a big issue, but I thought it would be best to not possibly send anyone to a 404.  Just FYI, most extensions simply use the corresponding repo's GitHub/GitLab/Codeberg/etc. main page for the support link on AMO.
